# Generated by Django 4.2.9 on 2024-01-06 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_question_belongs_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='belongs_to',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
