# Generated by Django 4.2.9 on 2024-01-06 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_question_topics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='topics',
            field=models.CharField(max_length=500),
        ),
    ]
