# Generated by Django 4.2.9 on 2024-01-06 23:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_question_topics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='topics',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None),
        ),
    ]
