# Generated by Django 4.2.9 on 2024-01-07 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_question_topics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
