# Generated by Django 4.2.9 on 2024-01-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_question_code_question_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
