# Generated by Django 4.2.9 on 2024-01-10 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_alter_question_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='generated_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
