# Generated by Django 4.2.9 on 2024-01-09 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discussion_question', models.CharField(max_length=100)),
                ('discussion_link', models.CharField(blank=True, max_length=250, null=True)),
                ('discussion_details', models.TextField(blank=True, null=True)),
                ('belongs_to', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
